blank_issues_enabled: true
contact_links:
    - name: Reach out to us via Discord
      url: https://discord.gg/jpbUFzS5Wb
      about:
          Get live support to resolve install, configuration, and technical
          issues not related to bugs/errors.
